import React, { FormEvent, useMemo, useState } from "react";

type Tab = "dashboard"|"pantry"|"basket"|"cookbook"|"coach"|"market"|"drivers"|"admin";
type PantryItem={id:string;name:string;qty:number;unit:string;expiresIn:number;category:string};
type CartItem={id:string;name:string;qty:number;store:string;price:number;approved:boolean};
type Order={id:string;status:string;stores:string[];total:number;safetyDone:boolean};
type State={pantry:PantryItem[];cart:CartItem[];orders:Order[];budget:number;coachTone:string;events:string[]};

const KEY="project220-v03-alpha";
const ADMIN_EMAIL="admin@project220.app";
const ADMIN_PASSWORD="Project220Admin!";
const stores=["No Frills","Giant Tiger","Walmart","Real Canadian Superstore","Safeway","Sobeys","FreshCo","Dollarama","Dollar Tree","Save-On-Foods","GNC","Popeye's Supplements"];
const seed:State={
 pantry:[
  {id:"p1",name:"Plain yogurt",qty:2,unit:"tubs",expiresIn:3,category:"Dairy"},
  {id:"p2",name:"Frozen berries",qty:1,unit:"bag",expiresIn:90,category:"Frozen"},
  {id:"p3",name:"Chicken breast",qty:1.5,unit:"kg",expiresIn:2,category:"Protein"},
  {id:"p4",name:"Brown rice",qty:1.8,unit:"kg",expiresIn:240,category:"Pantry"},
  {id:"p5",name:"Creatine monohydrate",qty:420,unit:"g",expiresIn:300,category:"Supplement"}
 ],
 cart:[
  {id:"c1",name:"Milk",qty:2,store:"No Frills",price:12.98,approved:true},
  {id:"c2",name:"Eggs",qty:2,store:"Walmart",price:9.94,approved:true},
  {id:"c3",name:"Spinach",qty:1,store:"FreshCo",price:3.99,approved:true},
  {id:"c4",name:"Whey protein",qty:1,store:"Popeye's Supplements",price:69.99,approved:true}
 ],
 orders:[],budget:140,coachTone:"Motivational",events:[]
};
function load():State{try{return {...seed,...JSON.parse(localStorage.getItem(KEY)||"{}")} as State}catch{return seed}}
function money(n:number){return new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD"}).format(n)}

export default function Project220AlphaApp(){
 const [logged,setLogged]=useState(false),[email,setEmail]=useState(ADMIN_EMAIL),[password,setPassword]=useState(ADMIN_PASSWORD),[error,setError]=useState("");
 const [tab,setTab]=useState<Tab>("dashboard"),[state,setState]=useState<State>(load),[notice,setNotice]=useState("");
 const save=(next:State)=>{setState(next);localStorage.setItem(KEY,JSON.stringify(next))};
 const log=(message:string)=>{const events=[`${new Date().toLocaleTimeString("en-CA")} — ${message}`,...state.events].slice(0,20);save({...state,events});setNotice(message);setTimeout(()=>setNotice(""),2800)};
 const login=(e:FormEvent)=>{e.preventDefault();if(email.toLowerCase()!==ADMIN_EMAIL||password!==ADMIN_PASSWORD){setError("Incorrect administrator login.");return}setLogged(true);setError("")};
 if(!logged)return <main style={ui.shell}><form onSubmit={login} style={ui.login}><h1>PROJECT <b style={ui.red}>220</b></h1><h2>Version 0.3 Alpha</h2><p>Master Admin testing account. Subscriber-private content is never shown here.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p style={ui.error}>{error}</p>}<button>Open Master Admin</button><small>Testing credentials are prefilled for this Alpha build.</small></form></main>;
 const total=state.cart.reduce((a,b)=>a+b.price,0),expiring=state.pantry.filter(x=>x.expiresIn<=5),score=Math.max(0,Math.min(100,82-expiring.length*3+Math.min(state.pantry.length,10)));
 return <main style={ui.shell}><section style={ui.app}>
  <header style={ui.header}><div><strong>PROJECT <span style={ui.red}>220</span></strong><small> v0.3 ALPHA · MASTER ADMIN</small></div><button onClick={()=>setLogged(false)}>Log out</button></header>
  <aside style={ui.privacy}><b>Privacy boundary:</b> Admin sees identity, subscription, billing status, address, orders and operations only. Health goals, pantry contents, photos, household profiles and private AI conversations remain subscriber-private.</aside>
  <nav style={ui.nav}>{(["dashboard","pantry","basket","cookbook","coach","market","drivers","admin"] as Tab[]).map(x=><button key={x} onClick={()=>setTab(x)} style={tab===x?ui.active:undefined}>{x}</button>)}</nav>
  {notice&&<div style={ui.notice}>{notice}</div>}
  {tab==="dashboard"&&<Panel title="Health & Grocery Operating System" sub="All Alpha modules share one local test-data store."><div style={ui.grid}><Card title="Smart Pantry Score" value={`${score}/100`} text={`${expiring.length} items need attention`}/><Card title="Basket total" value={money(total)} text={`${state.cart.length} items across ${new Set(state.cart.map(x=>x.store)).size} stores`}/><Card title="Budget" value={total<=state.budget?"On track":"Over budget"} text={`${money(Math.abs(state.budget-total))} ${total<=state.budget?"remaining":"over"}`}/><Card title="Active orders" value={String(state.orders.filter(x=>x.status!=="Delivered").length)} text="Unified cart fulfilment"}/><Card title="AI services" value="Alpha logic online" text="Provider adapters ready for credentials"}/><Card title="Private data" value="Blocked" text="Admin cannot open subscriber-private records"/></div></Panel>}
  {tab==="pantry"&&<Panel title="Pantry AI" sub="Barcode, receipt and photo workflows use local Alpha logic until live providers are connected."><div style={ui.actions}><button onClick={()=>{const item={id:crypto.randomUUID(),name:"Scanned bananas",qty:7,unit:"items",expiresIn:5,category:"Produce"};save({...state,pantry:[...state.pantry,item]});log("Demo barcode recognized and added after confirmation.")}}>Scan barcode</button><button onClick={()=>log("Receipt analysis found 6 products; confirmation is required before inventory changes.")}>Analyze receipt</button><button onClick={()=>log("Pantry photo processed; user selected automatic deletion after processing.")}>Process pantry photo</button></div><List>{state.pantry.map(p=><li key={p.id}><span><b>{p.name}</b><small>{p.qty} {p.unit} · {p.category} · expires in {p.expiresIn} days</small></span><button onClick={()=>save({...state,pantry:state.pantry.filter(x=>x.id!==p.id)})}>Use</button></li>)}</List></Panel>}
  {tab==="basket"&&<Panel title="Smart Basket Optimizer" sub="Cost, nutrition, supplement, budget, recipe and waste optimization."><div style={ui.grid}><Card title="Cost" value={money(total)} text="Cheapest-basket comparison ready"/><Card title="Nutrition" value="87/100" text="Add one fruit to improve balance"/><Card title="Supplements" value="No duplicate" text="Creatine supply estimated at 28 days"/><Card title="Recipes" value="9 unlocked" text="Using current pantry plus cart"/><Card title="Waste" value={`${expiring.length} protected`} text="Use-first meals prioritized"/><Card title="Budget" value={total<=state.budget?"Pass":"Review"} text={`Limit ${money(state.budget)}`}/></div><label style={ui.inline}>Weekly budget <input type="number" value={state.budget} onChange={e=>save({...state,budget:Number(e.target.value)})}/></label><button onClick={()=>log("Basket optimized: lower-cost equivalents suggested; no substitution applied without approval.")}>Run optimizer</button></Panel>}
  {tab==="cookbook"&&<Panel title="Premium Private Cookbook" sub="View-only, private recipes. Downloading, publishing and resale are disabled."><div style={ui.grid}>{[
   ["Berry Yogurt Crunch","Kid-friendly snack · 5 minutes"],["Frozen Yogurt Berry Bites","Healthy frozen snack · bulk-friendly"],["Chicken Rice Power Bowls","Family-size · meal prep"],["Banana Oat Mini Muffins","Kid-friendly · low added sugar"],["Salmon Potato Sheet Pan","Family dinner · one-pan"],["High-Protein Yogurt Parfait","Nutrition-plan snack"]
  ].map(r=><Card key={r[0]} title={r[0]} value="Open" text={r[1]}/>)}</div><button onClick={()=>log("Seven-day private cookbook generated from confirmed preferences and pantry data.")}>Generate private weekly cookbook</button></Panel>}
  {tab==="coach"&&<Panel title="AI Wellness Coach" sub="General wellness only; emergency and medical warnings are always displayed."><div style={ui.actions}>{["Supportive","Motivational","Performance","Elite"].map(t=><button key={t} style={state.coachTone===t?ui.active:undefined} onClick={()=>save({...state,coachTone:t})}>{t}</button>)}</div><article style={ui.darkCard}><h3>{state.coachTone} coaching</h3><p>Complete one planned meal, hydration target and movement session today. Use the pantry items expiring first.</p><b>Not medical care:</b> For urgent symptoms or an emergency, contact local emergency services.</article><button onClick={()=>log("Private wellness reminder scheduled. Admin can see delivery status, not message content.")}>Schedule reminders</button></Panel>}
  {tab==="market"&&<Panel title="Unified Marketplace" sub="Grocery and supplement items share one cart and one Project 220 checkout."><List>{state.cart.map(c=><li key={c.id}><span><b>{c.name}</b><small>{c.store} · {money(c.price)} · substitution {c.approved?"approved":"pending"}</small></span><button onClick={()=>save({...state,cart:state.cart.filter(x=>x.id!==c.id)})}>Remove</button></li>)}</List><div style={ui.actions}><button onClick={()=>log(`Compared ${stores.length} supported retailers using Alpha pricing data.`)}>Compare stores</button><button onClick={()=>{const order:Order={id:`P220-${Date.now().toString().slice(-6)}`,status:"Paid — preparing",stores:[...new Set(state.cart.map(x=>x.store))],total,safetyDone:false};save({...state,orders:[order,...state.orders]});log(`Order ${order.id} created. Live payment is disabled until processor credentials are connected.`)}}>Create Alpha order</button></div></Panel>}
  {tab==="drivers"&&<Panel title="Shopper & Driver Safety" sub="Completion is blocked until required food-handling evidence is recorded."><List>{state.orders.length?state.orders.map((o,i)=><li key={o.id}><span><b>{o.id}</b><small>{o.status} · {o.stores.join(", ")} · {money(o.total)}</small></span><button onClick={()=>{const orders=state.orders.map((x,n)=>n===i?{...x,safetyDone:true,status:"Safety verified — ready for delivery"}:x);save({...state,orders});log("Gloves/clean-hands confirmation, separation, sealed produce bags, weight labels and packing photos recorded.")}}>{o.safetyDone?"Verified":"Complete checklist"}</button></li>):<li>No Alpha orders yet.</li>}</List><p>Required checks: clean hands; correct glove use; raw-food separation; chemicals separated; produce bagged and zip-tied where required; quantity/weight labelled; cold/frozen insulation; clean cargo area; receipt and packing photos.</p></Panel>}
  {tab==="admin"&&<Panel title="Master Admin Operations" sub="Operational access without subscriber-private content."><div style={ui.grid}><Card title="Subscribers" value="1,248" text="Identity and subscription status only"/><Card title="Retailers" value={String(stores.length)} text="Grocery and supplement launch list"/><Card title="Payments" value="Provider needed" text="Full card data never stored"/><Card title="AI provider" value="Credentials needed" text="Adapter configuration documented"/><Card title="Private storage" value="Credentials needed" text="Photos isolated by subscriber"/><Card title="Audit log" value={String(state.events.length)} text="Operational events only"/></div><List>{state.events.map((e,i)=><li key={i}>{e}</li>)}</List><button onClick={()=>{localStorage.removeItem(KEY);setState(seed);setNotice("Alpha data reset.")}}>Reset Alpha data</button></Panel>}
 </section></main>
}
function Panel({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section><h1>{title}</h1><p style={ui.muted}>{sub}</p>{children}</section>}
function Card({title,value,text}:{title:string;value:string;text:string}){return <article style={ui.card}><b>{title}</b><strong>{value}</strong><small>{text}</small></article>}
function List({children}:{children:React.ReactNode}){return <ul style={ui.list}>{children}</ul>}
const ui:Record<string,React.CSSProperties>={shell:{minHeight:"100vh",background:"#0b0b0b",color:"#fff",fontFamily:"Arial,sans-serif"},app:{maxWidth:1120,margin:"auto",padding:"18px 16px 80px"},login:{maxWidth:430,margin:"auto",padding:32,display:"grid",gap:14},header:{display:"flex",justifyContent:"space-between",alignItems:"center",fontSize:22},red:{color:"#ef4444"},privacy:{background:"#17202a",borderLeft:"5px solid #22c55e",padding:14,margin:"18px 0",borderRadius:8},nav:{display:"flex",gap:8,overflowX:"auto",paddingBottom:12},active:{background:"#b91c1c",color:"white"},notice:{background:"#14532d",padding:12,borderRadius:8,marginBottom:14},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12},card:{background:"#1c1c1c",padding:16,borderRadius:10,display:"grid",gap:9,border:"1px solid #333"},darkCard:{background:"#171717",padding:18,borderRadius:10,margin:"12px 0"},list:{listStyle:"none",padding:0,display:"grid",gap:8},actions:{display:"flex",gap:8,flexWrap:"wrap",margin:"12px 0"},inline:{display:"flex",gap:10,alignItems:"center",margin:"16px 0"},muted:{color:"#c5c5c5"},error:{color:"#fecaca"}};
