import React, { FormEvent, useMemo, useState } from "react";

type PantryItem={name:string;qty:string;expires:number};
type CartItem={name:string;store:string;price:number};
type State={pantry:PantryItem[];recipes:string[];cart:CartItem[];coach:string;score:number;events:string[]};
const KEY="project220-sprint2";
const ADMIN={email:"admin@project220.app",password:"Project220Admin!"};
const initial:State={pantry:[{name:"Chicken breast",qty:"1.5 kg",expires:2},{name:"Plain yogurt",qty:"2 tubs",expires:3},{name:"Frozen berries",qty:"1 bag",expires:90},{name:"Brown rice",qty:"1.8 kg",expires:240},{name:"Creatine monohydrate",qty:"420 g",expires:300}],recipes:[],cart:[],coach:"",score:78,events:[]};
function load(){try{return {...initial,...JSON.parse(localStorage.getItem(KEY)||"{}")} as State}catch{return initial}}
function money(v:number){return new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD"}).format(v)}
export default function Project220Sprint2AI(){
 const [logged,setLogged]=useState(false),[email,setEmail]=useState(ADMIN.email),[password,setPassword]=useState(ADMIN.password),[error,setError]=useState("");
 const [state,setState]=useState<State>(load),[running,setRunning]=useState(false),[tab,setTab]=useState("command");
 const total=useMemo(()=>state.cart.reduce((s,x)=>s+x.price,0),[state.cart]);
 const save=(next:State)=>{setState(next);localStorage.setItem(KEY,JSON.stringify(next))};
 const login=(e:FormEvent)=>{e.preventDefault();if(email!==ADMIN.email||password!==ADMIN.password){setError("Incorrect Master Admin login.");return}setLogged(true);setError("")};
 async function run(){setRunning(true);await new Promise(r=>setTimeout(r,600));const now=new Date().toLocaleTimeString("en-CA");save({...state,recipes:["Chicken rice power bowls","Berry yogurt crunch","Frozen-yogurt berry bites","Kid-friendly banana oat cups","Pregnancy-friendly lentil and spinach bowl"],cart:[{name:"Spinach",store:"FreshCo",price:3.99},{name:"Milk",store:"No Frills",price:6.49},{name:"Bananas",store:"Walmart",price:2.68},{name:"Whey protein",store:"Popeye's Supplements",price:69.99}],coach:"Use the chicken and yogurt first. Complete one balanced meal, hydration target and planned workout today. General wellness guidance only.",score:92,events:[`${now} Pantry, receipt and barcode AI completed.`,`${now} Expiration and waste-prevention AI prioritized 2 items.`,`${now} Cookbook AI generated 5 private recipes.`,`${now} Nutrition AI included pregnancy and life-stage safeguards.`,`${now} Smart Basket Optimizer built a demo cart.`,`${now} AI Coach generated private guidance.`,...state.events].slice(0,20)});setRunning(false)}
 if(!logged)return <main style={ui.shell}><form style={ui.login} onSubmit={login}><h1>PROJECT <span style={ui.red}>220</span></h1><h2>Sprint 2 Connected AI Alpha</h2><p>Master Admin operates synthetic AI workflows without accessing subscriber-private information.</p><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p style={ui.error}>{error}</p>}<button style={ui.primary}>Sign in</button></form></main>;
 const tabs=["command","pantry","nutrition","cookbook","coach","basket","privacy"];
 return <main style={ui.shell}><section style={ui.app}><header style={ui.header}><b>PROJECT <span style={ui.red}>220</span> · SPRINT 2</b><button onClick={()=>setLogged(false)}>Log out</button></header><aside style={ui.privacy}><b>Privacy boundary:</b> Admin can test services and see system status, but cannot open private photos, health data, household profiles, personal plans or AI conversations.</aside><nav style={ui.nav}>{tabs.map(x=><button key={x} onClick={()=>setTab(x)} style={tab===x?ui.active:undefined}>{x}</button>)}</nav>
 {tab==="command"&&<section><h1>Connected AI Command Centre</h1><button style={ui.primary} disabled={running} onClick={run}>{running?"Running ecosystem…":"Run Full AI Ecosystem"}</button><div style={ui.grid}><Card t="Smart Pantry Score" v={`${state.score}/100`} d="Freshness, readiness, nutrition and waste"/><Card t="Private recipes" v={String(state.recipes.length)} d="Family, kid and pregnancy-aware"/><Card t="Demo basket" v={money(total)} d={`${state.cart.length} optimized items`}/><Card t="AI Coach" v={state.coach?"Ready":"Waiting"} d="Private general-wellness guidance"/></div><Panel title="Activity">{state.events.length?<ul>{state.events.map((e,i)=><li key={i}>{e}</li>)}</ul>:<p>Run the ecosystem to begin testing.</p>}</Panel></section>}
 {tab==="pantry"&&<Panel title="Pantry, Receipt & Barcode AI"><button onClick={()=>save({...state,pantry:[...state.pantry,{name:"Scanned bananas",qty:"7 items",expires:5}]})}>Simulate barcode scan</button><ul>{state.pantry.map((x,i)=><li key={i}><b>{x.name}</b> — {x.qty} — expires in {x.expires} days</li>)}</ul></Panel>}
 {tab==="nutrition"&&<Panel title="Universal Nutrition AI"><p>Supports infant, child, preteen, teen, adult, elderly and pregnancy profiles, plus allergies, dietary preferences and clinician instructions.</p><button onClick={()=>save({...state,events:[`${new Date().toLocaleTimeString("en-CA")} Generated a synthetic pregnancy-safe nutrition plan with food-safety warnings.`,...state.events]})}>Generate pregnancy-safe demo plan</button></Panel>}
 {tab==="cookbook"&&<Panel title="Premium Private Cookbook">{state.recipes.length?<ul>{state.recipes.map(x=><li key={x}>{x}</li>)}</ul>:<p>Run the ecosystem to generate recipes.</p>}</Panel>}
 {tab==="coach"&&<Panel title="AI Wellness Coach"><p>{state.coach||"Run the ecosystem to generate coaching."}</p><small>Not medical care. Urgent concerns require local emergency or professional medical support.</small></Panel>}
 {tab==="basket"&&<Panel title="Smart Basket Optimizer">{state.cart.length?<ul>{state.cart.map(x=><li key={x.name}>{x.name} — {x.store} — {money(x.price)}</li>)}</ul>:<p>Run the ecosystem to build the basket.</p>}<p>Cost, nutrition, supplement, budget, recipe and waste optimization are connected in demo mode.</p></Panel>}
 {tab==="privacy"&&<Panel title="Privacy Controls"><p>Only first and last name, account contact, subscription status, delivery address when required, and payment-provider status are operationally necessary. Private subscriber content remains inaccessible to routine admin access.</p></Panel>}
 </section></main>
}
function Card({t,v,d}:{t:string;v:string;d:string}){return <article style={ui.card}><b>{t}</b><strong>{v}</strong><small>{d}</small></article>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section style={ui.panel}><h2>{title}</h2>{children}</section>}
const ui:Record<string,React.CSSProperties>={shell:{minHeight:"100vh",background:"#080808",color:"white",fontFamily:"Arial,sans-serif"},app:{maxWidth:1100,margin:"auto",padding:"18px 16px 70px"},login:{maxWidth:440,margin:"auto",padding:"46px 20px",display:"grid",gap:14},header:{display:"flex",justifyContent:"space-between",alignItems:"center",fontSize:20},red:{color:"#ef4444"},privacy:{background:"#17202a",borderLeft:"5px solid #22c55e",padding:14,borderRadius:10,margin:"16px 0"},nav:{display:"flex",gap:8,overflowX:"auto",paddingBottom:14},active:{background:"#991b1b",color:"white"},primary:{background:"#b91c1c",color:"white",border:0,borderRadius:8,padding:"12px 16px",fontWeight:700},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12,marginTop:16},card:{background:"#171717",border:"1px solid #333",borderRadius:10,padding:16,display:"grid",gap:8},panel:{background:"#151515",border:"1px solid #303030",borderRadius:10,padding:18,marginTop:14},error:{color:"#fecaca"}};